export const ADD_COMMENT = "ADD_COMMENT";

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CART_LOADING = 'CART_LOADING';
export const CART_FAILED = 'CART_FAILED';

export const INCREMENT = 'INCREMENT';
export const INCREMENT_FAILED = 'INCREMENT_FAILED';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_FAILED = 'DECREMENT_FAILED';

export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_ITEM_FAILED = 'REMOVE_ITEM_FAILED';

export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART_FAILED = 'CLEAR_CART_FAILED';

export const ADD_TOTALS = 'ADD_TOTALS';
export const ADD_TOTALS_FAILED = 'ADD_TOTALS_FAILED';


