export const ADD_COMMENT = "ADD_COMMENT";

export const ADD_FEEDBACK = "ADD_FEEDBACK";

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

