export const storeProducts = [
    {
        id: 0,
        title: "Google Pixel",
        image: "./img/product-1.png",
        price: 59999,
        company: "GOOGLE",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: 'Hot',
        featured: true,
    },
    {
        id: 1,
        title: "Samsung S7",
        image: "./img/product-2.png",
        price: 5799,
        company: "SAMSUNG",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 2,
        title: "HTC 10 - Black",
        image: "./img/product-3.png",
        price: 56690,
        company: "htc",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 3,
        title: "HTC 10 - White",
        image: "./img/product-4.png",
        price: 57299,
        company: "htc",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 4,
        title: "HTC Desire 626s",
        image: "./img/product-5.png",
        price: 4900,
        company: "htc",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 5,
        title: "Iphone 5S",
        image: "./img/product-6.png",
        price: 15999,
        company: "apple",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 6,
        title: "Iphone 7",
        image: "./img/product-7.png",
        price: 29499,
        company: "apple",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
    {
        id: 7,
        title: "Smashed Iphone",
        image: "./img/product-8.png",
        price: 10499,
        company: "apple",
        info:
            "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.",
        inCart: false,
        count: 0,
        total: 0,
        label: '',
        featured: false,
    },
];